# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import datetime

from PyQt5 import QtCore, QtGui, QtWidgets
import Progect
from config import pattern
import re
import json

def parse(line):
    

    line = line.replace("(", "").replace(")", "").replace("'", "")

    log_parts = line.split(", ")
    for i in log_parts:
        print(i)
    return log_parts

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(0, 0, 151, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(170, 0, 151, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(340, 0, 201, 28))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(550, 0, 221, 28))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(0, 40, 221, 28))
        self.pushButton_5.setObjectName("pushButton_5")
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.centralwidget)
        self.dateTimeEdit.setGeometry(QtCore.QRect(230, 40, 194, 22))
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.dateTimeEdit.setDate(QtCore.QDate(2022, 12, 7))
        self.dateTimeEdit.setTime(QtCore.QTime(10, 20, 0))
        self.dateTimeEdit_2 = QtWidgets.QDateTimeEdit(self.centralwidget)
        self.dateTimeEdit_2.setGeometry(QtCore.QRect(440, 40, 194, 22))
        self.dateTimeEdit_2.setObjectName("dateTimeEdit_2")
        self.dateTimeEdit_2.setDate(QtCore.QDate(2022, 12, 12))
        self.dateTimeEdit_2.setTime(QtCore.QTime(11, 26, 13))
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(0, 80, 221, 28))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(0, 110, 221, 28))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(0, 140, 221, 28))
        self.pushButton_8.setObjectName("pushButton_8")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(60, 220, 531, 311))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setLayout(QtWidgets.QVBoxLayout())
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 529, 309))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.pushButton.clicked.connect(self.add_data_to_scroll_area)
        self.pushButton_2.clicked.connect(self.output_data_to_scroll_area)
        self.pushButton_3.clicked.connect(self.output_data_time_to_scroll)
        self.pushButton_4.clicked.connect(self.output_by_ip_to_scroll)
        self.pushButton_5.clicked.connect(self.date_between)
        self.pushButton_6.clicked.connect(self.output_json_by_ip_to_scroll)
        self.pushButton_7.clicked.connect(self.output_json_group_by_ip_to_scroll)
        self.pushButton_8.clicked.connect(self.output_json_group_by_date_to_scroll)



        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Добавление данных"))
        self.pushButton_2.setText(_translate("MainWindow", "Вывод данных"))
        self.pushButton_3.setText(_translate("MainWindow", "Вывод группированных по дате"))
        self.pushButton_4.setText(_translate("MainWindow", "Вывод группированных IP адрессу"))
        self.pushButton_5.setText(_translate("MainWindow", "Вывод с фильтром по датам"))
        self.pushButton_6.setText(_translate("MainWindow", "Вывод json группированного по IP"))
        self.pushButton_7.setText(_translate("MainWindow", "Вывод json фильтрованного по IP"))
        self.pushButton_8.setText(_translate("MainWindow", "Вывод json c фильтром по датам"))
        

    def add_data_to_scroll_area(self):
        self.clear_scroll()
        data = Progect.make_connect(1)
        label = QtWidgets.QLabel()
        label.setText(data)

        layout = self.scrollAreaWidgetContents.layout()

        layout.addWidget(label)


    def output_data_to_scroll_area(self):
        self.clear_scroll()
        data = Progect.make_connect(2)
        layout = self.scrollAreaWidgetContents.layout()

        for a in data:
            string_data = ' '.join(str(element) for element in a)
            line = parse(string_data) 
            text = ""
            for i in range(len(line)):
                text += line[i]
            label = QtWidgets.QLabel()
            label.setText(text)  
            layout.addWidget(label)


    def output_data_time_to_scroll(self):
        self.clear_scroll()
        text = ""
        data = Progect.make_connect(3)
        for i in data:
            text += i + "\n"
        layout = self.scrollAreaWidgetContents.layout()
        label = QtWidgets.QLabel()
        label.setText(text)
        layout.addWidget(label)


    def clear_scroll(self):
        layout = self.scrollAreaWidgetContents.layout()
        while layout.count():
            item = layout.takeAt(0)
            widget = item.widget()
            if widget:
                widget.deleteLater()


    def output_by_ip_to_scroll(self):
        
        self.clear_scroll()
        text = ""
        data = Progect.make_connect(4)
        for i in data:
            text += i + "\n"
        layout = self.scrollAreaWidgetContents.layout()
        label = QtWidgets.QLabel()
        label.setText(text)
        layout.addWidget(label)

    def output_json_by_ip_to_scroll(self):
        
        self.clear_scroll()
        text = ""
        
        data = Progect.make_connect(6)
        layout = self.scrollAreaWidgetContents.layout()
        label = QtWidgets.QLabel()
        label.setText(data)
        layout.addWidget(label)
    def output_json_group_by_ip_to_scroll(self):
        self.clear_scroll()
        text = ""
        
        data = Progect.make_connect(7)
        layout = self.scrollAreaWidgetContents.layout()
        label = QtWidgets.QLabel()
        label.setText(data)
        layout.addWidget(label)
    def date_between(self):
        self.clear_scroll()

        first_date = self.dateTimeEdit.dateTime()
        first_date = first_date.toString("yyyy-MM-dd hh:mm:ss")
        second_date = self.dateTimeEdit_2.dateTime().toString("yyyy-MM-dd hh:mm:ss")
        data = Progect.make_connect(5, first_date, second_date)
        layout = self.scrollAreaWidgetContents.layout()
        for a in data:
            string_data = ' '.join(str(element) for element in a)
            line = parse(string_data) 
            text = ""
            for i in range(len(line)):
                text += line[i]
            label = QtWidgets.QLabel()
            label.setText(text)  
            layout.addWidget(label)        
            label = QtWidgets.QLabel()
        layout.addWidget(label)
    def output_json_group_by_date_to_scroll(self):
        self.clear_scroll()
        text = ""
        
        data = Progect.make_connect(8)
        layout = self.scrollAreaWidgetContents.layout()
        label = QtWidgets.QLabel()
        label.setText(data)
        layout.addWidget(label)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
